### ISSUE TITLE
PaperMC Downloads API no longer offers velocity

### ISSUE THREAD

**Issue by CCF100** [PaperMC/bibliothek#115]
I'm rewriting my server updater in Java, and I noticed that velocity is no longer offered by the API... Is there any reason why?

**Comment by electronicboy** [comment]
<img width="1463" alt="image" src="https://user-images.githubusercontent.com/1228900/204766369-fe65d436-3a1d-452d-9485-20dd9a0ed9c4.png">
It's still in there
