### ISSUE TITLE
bibliothek fails when attempting to release a new version

### ISSUE THREAD

**Issue by electronicboy** [PaperMC/bibliothek#13]
```
TypeError: Cannot read property '_id' of null
    at run (/home/library/repository/cli/insertBuild.js:138:32)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

it appears that the cli tool will crash when a previous build for that release does not crash, it will however seemingly leave some stuff dangling in the breeze, so subsequent pushes work fine

**Comment by kashike** [comment]
https://github.com/PaperMC/bibliothek/commit/e5d45441784bd49459b1a6db544b4fc142ce6f4a
