### ISSUE TITLE
deploy to github container registry

### ISSUE THREAD

**Issue by kashike** [PaperMC/bibliothek#148]
```[tasklist]
- [ ] #147
- [x] deploy to github container registry
```

**Comment by rtm516** [comment]
Just done this with our fork https://github.com/GeyserMC/bibliothek/blob/main/.github/workflows/build.yml

**Comment by kashike** [comment]
https://github.com/PaperMC/bibliothek/commit/9bd80f88c2f521159e9b34aea1c8a3b089f0d8c9
https://github.com/PaperMC/bibliothek/commit/d168b4d914a41cf1cbab9657111602aae86e393a
