### ISSUE TITLE
How can i get mc latest version

### ISSUE THREAD

**Issue by 8MiYile** [PaperMC/bibliothek#58]
https://papermc.io/api/v1/paper/lastversion/latest/download

**Comment by electronicboy** [comment]
There is no latest endpoint, that is intentional, querying the API is the only way to do this, v1 API is scheduled to be sunset

**Comment by 8MiYile** [comment]
oh i just want update mc version 
wget

**Comment by electronicboy** [comment]
Go to the downloads page, right click on the download button for the build, copy link

**Comment by kangarko** [comment]
For anyone looking I have made getting the latest version possible (and not only for Paper): https://mineacademy.org/endpoint
