### ISSUE TITLE
Add a /latest endpoint for /v2 API

### ISSUE THREAD

**Issue by Darkilen** [PaperMC/bibliothek#74]
Hello,
Could you consider adding a `/latest` endpoint for the `v2` API ?
It's very usefull to update a server without setting the build number each time.

**Comment by electronicboy** [comment]
No, as has been discussed many times, we have 0 interest in maintaining such an endpoint and all the issues it induces

**Comment by Darkilen** [comment]
I may have been wrong in my way of expressing myself, what I would like is to have an endpoint `/v2/projects/{project}/versions/{version}/build/latest` (with or without `/download` at the end) to grab the latest build for a specific version in a specific project instead of having to retrieve the list of all builds for a specific project then find and download the latest version with a custom script.

It would help us automatic our upgrade process and limit the number of request sent to your API.

If you are not willing to (re)implement this, are you open for a PR ?

**Comment by MiniDigger** [comment]
thats exactly what we don't want to do.
we don't want people to blindly out update.
every build should be manually validated.
we aren't concerned about amount of requests, the api is 100% cached by cloudflare.
we will not accept an api to add that, sorry.

**Comment by Darkilen** [comment]
Thanks for the explanation, I understand your point.
We do validate every update manually on a pre-production server, but currently, it's a pain to pull the latest build. So we'll do something on our end about this issue.
