### ISSUE TITLE
Missing versions for `1.13-pre7`

### ISSUE THREAD

**Issue by Cherry** [PaperMC/bibliothek#83]
As of this morning, `1.13-pre7` no longer has any versions in the API, or it's erroneously returned.

`https://papermc.io/api/v2/projects/paper` returns 1.13-pre7 as an available version. But then
`https://papermc.io/api/v2/projects/paper/versions/1.13-pre7` 404s.

**Comment by HexedHero** [comment]
Keeping pre releases sound like a waste of space, why are you even using it?

**Comment by Cherry** [comment]
> Keeping pre releases sound like a waste of space, why are you even using it?

We're not. But it tripped up some of our automation which expected there to be builds for all reported versions at https://papermc.io/api/v2/projects/paper. If there's no available builds for it (which it appears so), it should probably just be removed from the `versions` returned there.
